// Generate src/catalog.js from the TeX files that are actually vendored.
//
// TikZJax can only load a library or package whose (gzipped) TeX source sits in
// vendor/tikzjax/tex_files, so the offer in the user interface is derived from
// that directory rather than written by hand: nothing can be offered that would
// then fail to compile.
//
//     node tools/gen-catalog.mjs
//
// tools/fetch-vendor.sh runs this after re-vendoring.
import { readdir, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const texFiles = join(root, 'vendor', 'tikzjax', 'tex_files');

// Packages that are here because something else needs them, not because anyone
// would choose them; offering these would only invite confusion.  A preamble
// can still \usepackage any of them by hand.
const INTERNAL = new Set([
    'expl3', 'amsgen', 'pgfcalendar', 'l3backend-dvips',
    // loaded on quantikz's behalf
    'mhsetup', 'trimspaces', 'xkeyval', 'xkvutils', 'keyval', 'environ', 'xargs'
]);

const files = (await readdir(texFiles)).map((f) => f.replace(/\.gz$/, ''));

// \usetikzlibrary{X} loads tikzlibraryX.code.tex when there is one and falls
// back to pgflibraryX.code.tex, so both spellings are offerable -- arrows.meta,
// for one, exists only in the pgf form.
const libraryNames = (prefix) => files
    .filter((f) => f.startsWith(prefix) && f.endsWith('.code.tex'))
    .map((f) => f.slice(prefix.length, -'.code.tex'.length));

// Support files rather than libraries anyone loads by name.
const NOT_A_LIBRARY = new Set(['pgfplots.surfshading', 'bbox']);

const libraries = [...new Set([...libraryNames('tikzlibrary'), ...libraryNames('pgflibrary')])]
    .filter((l) => !NOT_A_LIBRARY.has(l))
    .sort();

const packages = files
    .filter((f) => f.endsWith('.sty'))
    .map((f) => f.slice(0, -'.sty'.length))
    .filter((p) => !INTERNAL.has(p))
    .sort();

if (!libraries.length || !packages.length) {
    throw new Error(`no TeX files found in ${texFiles} -- run tools/fetch-vendor.sh first`);
}

const list = (items) => items.map((i) => `    '${i}'`).join(',\n');

await writeFile(join(root, 'src', 'catalog.js'), `// Generated by tools/gen-catalog.mjs from vendor/tikzjax/tex_files -- do not edit.
//
// Every name here has its TeX source vendored, so requesting it always works,
// offline included.

/** TikZ libraries loadable with \\usetikzlibrary. @type {readonly string[]} */
export const TIKZ_LIBRARIES = [
${list(libraries)}
];

/** TeX packages loadable with \\usepackage. @type {readonly string[]} */
export const TEX_PACKAGES = [
${list(packages)}
];
`);

console.log(`src/catalog.js: ${libraries.length} TikZ libraries, ${packages.length} TeX packages`);
